//! Raw FFI bindings to **libMTL** (`mtlslib`), generated by `bindgen`.
//!
//! This crate exposes the C entry points that underlie the upstream
//! `mtlkeygen` / `mtlsign` / `mtlverify` CLI tools. It contains **no**
//! hand-written cryptographic logic — every symbol here is emitted by
//! `bindgen` from the vendored, pinned headers at build time.
//!
//! # Header discovery (Phase 2.1)
//!
//! The public API lives in `mtllib.h`. It transitively includes `mtl.h`
//! (types: [`MTL_CTX`], [`MTL_HANDLE`]), `mtllib_buffer.h`
//! ([`MTLLIB_BUFFER`]) and `mtllib_status.h` ([`MTLLIB_STATUS`]). The
//! CLI-only argument parsing in upstream `examples/mtl*.c` is intentionally
//! not bound.
//!
//! # Build configuration
//!
//! Point the build at an install prefix with `CLIMB_MTL_PREFIX` (or
//! `CLIMB_MTL_INCLUDE` / `CLIMB_MTL_LIB`). See `build.rs` for the full
//! resolution order. Run `docker/extract-libs.sh` to populate the default
//! `<workspace>/.mtl-install` prefix from the pinned Docker builder image.
//!
//! # Safety
//!
//! Every function in this crate is an `unsafe` FFI call. Pointers must be
//! non-null, correctly aligned, and owned by libMTL where the C API says so.
//! Buffers passed to the library must stay alive for the duration of a call.
//! Prefer the future safe wrapper in `climb-mtl`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
// bindgen doc comments occasionally contain `[` characters from C syntax that
// rustdoc would otherwise try to resolve as intra-doc links.
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::invalid_html_tags)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Human-readable library version string reported by the vendored libMTL.
///
/// Sourced from `MTL_LIB_VERSION` in `mtl.h`. Kept as a Rust constant so
/// callers can report which reference implementation was linked without
/// reaching into the generated bindings.
pub const MTL_LIB_VERSION: &str = "v1.2.1";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bindings_are_generated() {
        // The generated bindings define the MTLLIB_STATUS enum with MTLLIB_OK.
        assert_eq!(MTLLIB_STATUS_MTLLIB_OK, 0);
    }

    #[test]
    fn status_and_scheme_entry_points_exist() {
        // Compile-time proof that the expected public API was bound. Taking the
        // address of each symbol forces it to exist without calling into C.
        let _ = mtllib_key_new as unsafe extern "C" fn(*mut i8, *mut *mut MTLLIB_CTX) -> u32;
        let _ = mtllib_sign_append
            as unsafe extern "C" fn(
                *mut MTLLIB_CTX,
                *mut MTLLIB_BUFFER,
                *mut *mut MTL_HANDLE,
            ) -> u32;
        let _ = mtllib_verify
            as unsafe extern "C" fn(
                *mut MTLLIB_CTX,
                *mut MTLLIB_BUFFER,
                *mut MTLLIB_BUFFER,
                *mut MTLLIB_BUFFER,
                *mut usize,
            ) -> u32;
    }
}
